version: '3.5'
services:
  php-apache:
    build: .
    container_name: php-apache
    ports:
      - '80:80'
    volumes:
      - './:/var/www/html/'
    depends_on:
      - db

  db:
    image: mariadb
    container_name: db
    volumes:
      - './db:/var/lib/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: root

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    ports:
      - '8080:80'
    environment:
      MYSQL_ROOT_PASSWORD: root
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - db
